/** This class auto-generated by org.synchronoss.utils.cpo.Proxy **/

package org.synchronoss.cpo.meta.bean;

public class CpoArgumentBean implements java.io.Serializable {

  /* Properties */
  private java.lang.String attributeName;
  private java.lang.String description;

  public CpoArgumentBean() {
  }

  public String getAttributeName() {
    return attributeName;
  }

  public void setAttributeName(String attributeName) {
    this.attributeName = attributeName;
  }

  public String getDescription() {
    return description;
  }

  public void setDescription(String description) {
    this.description = description;
  }

  /* Getters and Setters */

  public boolean equals(Object o) {
    if (this == o)
      return true;
    if (o == null || getClass() != o.getClass())
      return false;

    CpoArgumentBean that = (CpoArgumentBean)o;

    if (getAttributeName() != null ? !getAttributeName().equals(that.getAttributeName()) : that.getAttributeName() != null)
      return false;
    if (getDescription() != null ? !getDescription().equals(that.getDescription()) : that.getDescription() != null)
      return false;

    return true;
  }

  public int hashCode() {
    int result = 0;
    result = 31 * result + getClass().getName().hashCode();
    result = 31 * result + (getAttributeName() != null ? getAttributeName().hashCode() : 0);
    result = 31 * result + (getDescription() != null ? getDescription().hashCode() : 0);
    return result;
  }

  public String toString() {
    StringBuilder str = new StringBuilder();
    str.append("attributeName = " + getAttributeName() + "\n");
    str.append("description = " + getDescription() + "\n");
    return str.toString();
  }
}
