/** This class auto-generated by org.synchronoss.utils.cpo.Proxy **/

package org.synchronoss.cpo.meta.bean;

public class CpoClassBean implements java.io.Serializable {

  /* Properties */
  private java.lang.String name;
  private java.lang.String description;

  public CpoClassBean() {
  }
  
  public CpoClassBean(String name) {
    this.name = name;
  }

  /* Getters and Setters */
  public java.lang.String getName() {
    return this.name;
  }
  public void setName(java.lang.String name) {
    this.name = name;
  }

  public String getDescription() {
    return description;
  }

  public void setDescription(String description) {
    this.description = description;
  }

  public boolean equals(Object o) {
    if (this == o)
      return true;
    if (o == null || getClass() != o.getClass())
      return false;

    CpoClassBean that = (CpoClassBean)o;

    if (getName() != null ? !getName().equals(that.getName()) : that.getName() != null)
      return false;
    if (getDescription() != null ? !getDescription().equals(that.getDescription()) : that.getDescription() != null)
      return false;

    return true;
  }

  public int hashCode() {
    int result = 0;
    result = 31 * result + getClass().getName().hashCode();
    result = 31 * result + (getName() != null ? getName().hashCode() : 0);
    result = 31 * result + (getDescription() != null ? getDescription().hashCode() : 0);
    return result;
  }

  public String toString() {
    StringBuilder str = new StringBuilder();
    str.append("name = " + getName() + "\n");
    str.append("description = " + getDescription() + "\n");
    return str.toString();
  }
}
