package org.synchronoss.cpo.core.exporter;

/*-
 * [[
 * core
 * ==
 * Copyright (C) 2003 - 2025 David E. Berry
 * ==
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU Lesser General Public License as
 * published by the Free Software Foundation, either version 3 of the
 * License, or (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Lesser Public License for more details.
 *
 * You should have received a copy of the GNU General Lesser Public
 * License along with this program.  If not, see
 * <http://www.gnu.org/licenses/lgpl-3.0.html>.
 * ]]
 */

import org.synchronoss.cpo.core.meta.CpoMetaDescriptor;
import org.synchronoss.cpo.core.meta.domain.CpoAttribute;
import org.synchronoss.cpo.core.meta.domain.CpoClass;

/**
 * The CpoInterfaceSourceGenerator generates java source code to define the cpo interfaces.
 *
 * @author Michael Bellomo
 * @since 4/17/12
 */
public class CpoInterfaceSourceGenerator extends AbstractMetaVisitor {

  protected CpoMetaDescriptor metaDescriptor;
  protected String interfaceName = null;
  protected StringBuilder header = new StringBuilder();
  protected StringBuilder footer = new StringBuilder();

  public CpoInterfaceSourceGenerator(CpoMetaDescriptor metaDescriptor) {
    this.metaDescriptor = metaDescriptor;
  }

  /**
   * Resets all of the buffers.
   *
   * <p>This is needed if you intend to reuse the visitor. This is always called by visit(CpoClass)
   */
  private void reset() {
    attributeStatics = new StringBuilder();
    functionGroupStatics = new StringBuilder();
    gettersSetters = new StringBuilder();
    footer = new StringBuilder();
  }

  public String getInterfaceName() {
    return interfaceName;
  }

  public String getSourceCode() {
    StringBuilder source = new StringBuilder();

    source.append("/* \n");
    source.append(" *  This interface auto-generated by " + this.getClass().getName() + "\n");
    source.append(" */\n");
    source.append(header);
    source.append("\n  /* Attribute name statics */\n");
    source.append(attributeStatics);
    source.append("\n  /* Function group statics */\n");
    source.append(functionGroupStatics);
    source.append("\n  /* Getters and Setters */\n");
    source.append(gettersSetters);

    source.append(footer);
    source.append("\n");

    return source.toString();
  }

  /** Returns the name of the class to use */
  protected String generateInterfaceName(CpoClass cpoClass) {
    String className = cpoClass.getName();
    if (className.lastIndexOf(".") != -1) {
      className = className.substring(className.lastIndexOf(".") + 1);
    }
    return className;
  }

  @Override
  public void visit(CpoClass cpoClass) {

    // reset all the buffers
    reset();

    interfaceName = generateInterfaceName(cpoClass);

    // generate class header
    header.append(buildPackageName(cpoClass));

    // generate interface declaration
    header.append("public interface " + interfaceName + " {\n");

    // footer
    footer.append("}\n");
  }

  @Override
  public void visit(CpoAttribute cpoAttribute) {

    String attName = scrubName(cpoAttribute.getJavaName());

    String getterName = buildGetterName(attName);
    String setterName = buildSetterName(attName);

    String attClassName = cpoAttribute.getJavaType();

    // generate attribute statics
    attributeStatics.append(buildAttributeStatic(attName));

    // generate getter
    gettersSetters.append("  public " + attClassName + " " + getterName + ";\n");

    // generate setter
    gettersSetters.append(
        "  public void " + setterName + "(" + attClassName + " " + attName + ");\n");
    gettersSetters.append("\n");
  }
}
