package org.synchronoss.cpo.core.exporter;

/*-
 * [[
 * core
 * ==
 * Copyright (C) 2003 - 2025 David E. Berry
 * ==
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU Lesser General Public License as
 * published by the Free Software Foundation, either version 3 of the
 * License, or (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Lesser Public License for more details.
 *
 * You should have received a copy of the GNU General Lesser Public
 * License along with this program.  If not, see
 * <http://www.gnu.org/licenses/lgpl-3.0.html>.
 * ]]
 */

import org.synchronoss.cpo.core.meta.CpoMetaDescriptor;
import org.synchronoss.cpo.core.meta.domain.CpoClass;

/**
 * The CpoClassSourceGenerator generates java source code to define the cpo classes.
 *
 * <p>This implemenation will generate only a class, without extending an interface. It is available
 * to support existing systems that aren't able/willing to change to the interface model.
 *
 * @author Michael Bellomo
 * @since 4/17/12
 */
public class CpoLegacyClassSourceGenerator extends CpoClassSourceGenerator {

  public CpoLegacyClassSourceGenerator(CpoMetaDescriptor metaDescriptor) {
    super(metaDescriptor);
  }

  public String getSourceCode() {
    StringBuilder source = new StringBuilder();

    source.append("/* \n");
    source.append(" *  This class auto-generated by " + this.getClass().getName() + "\n");
    source.append(" */\n");
    source.append(header);
    source.append("\n  /* Attribute name statics */\n");
    source.append(attributeStatics);
    source.append("\n  /* Function group statics */\n");
    source.append(functionGroupStatics);

    appendClassBody(source);

    return source.toString();
  }

  /** Returns the name of the class to use */
  protected String generateClassName(CpoClass cpoClass) {
    return super.generateInterfaceName(cpoClass);
  }

  @Override
  public void visit(CpoClass cpoClass) {

    // reset all the buffers
    reset();

    className = generateClassName(cpoClass);

    // generate class header
    header.append(buildPackageName(cpoClass));

    // generate class declaration
    header.append("public class " + className + " implements java.io.Serializable {\n");
    header.append("  private static final long serialVersionUID = 1L;\n");
    // footer
    footer.append("}\n");

    // generate constructor
    constructor.append("  public " + className + "() {\n");
    constructor.append("  }\n");
  }
}
